gui:
  scrollHeight: 4 # how many lines you scroll by
  scrollPastBottom: false # enable scrolling past the bottom
  border: rounded
  filterMode: fuzzy
os:
  edit: 'nvim {{filename}}' # see 'Configuring File Editing' section
  editAtLine: 'nvim +{{line}} -- {{filename}}'
git:
  pagers:
    - colorArg: always
      pager: delta --light --paging=never
promptToReturnFromSubprocess: false
